version: 0.0
os: linux
files:
   - source: /
     destination: /usr/local/nginx/html/prueba
permissions:
   - object: /usr/local/nginx/html/prueba
     pattern: "**"
     owner: nginx
     group: nginx
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
